### ISSUE TITLE
Request for documentation

### ISSUE THREAD

**Issue by siddharthist** [akhenakh/statgo#1]
As of right now, the documentation is limited to the README and a godoc that isn't linked to from the Github page. The godoc itself doesn't provide necessary information, such as what units many metrics are given in. I'd love to use this library, but this is a big barrier.

**Comment by akhenakh** [comment]
hope it helps: cd88f936d3dc35b57d56c923c7593e03539c451b

**Comment by siddharthist** [comment]
@akhenakh Absolutely. Thank you! I'll let you know if I have any other questions.

**Comment by siddharthist** [comment]
@akhenakh Would you like me to put in a PR with a link to the godoc from the README? Might be helpful for those looking to use your work.

**Comment by akhenakh** [comment]
Here you go cda95502c557c3fab01821edbb1a43f7e225dd92
