### ISSUE TITLE
goroutine leak

### ISSUE THREAD

**Issue by mia0x75** [akhenakh/statgo#11]
```
package main

import (
	"fmt"
	"runtime"
	"time"

	"github.com/akhenakh/statgo"
)

func main() {
	go func() {
		d := time.Duration(1) * time.Second
		for range time.Tick(d) {
			fmt.Printf("Total goroutines: %d\n", runtime.NumGoroutine())
		}
	}()

	for {
		d := time.Duration(1) * time.Second
		statgo.NewStat()
		time.Sleep(d)
	}
}
```

**Comment by akhenakh** [comment]
This is not how this lib is intended to be used.
Because of libstatgrab only one NewStat can be called at a time.

Simply change the time.Tick to 2 seconds and you will see the newly allocated stats will be garbage collected.

But you are right this should be mentioned in the documentation

**Comment by mia0x75** [comment]
The total goroutine count keeps growing even if I change the time.Tick to 5 seconds. 

```
$ go run main.go 
Total goroutines: 3
Total goroutines: 4
Total goroutines: 5
Total goroutines: 6
Total goroutines: 7
Total goroutines: 8
Total goroutines: 9
Total goroutines: 10
Total goroutines: 11
Total goroutines: 12
Total goroutines: 13
Total goroutines: 14
Total goroutines: 15
Total goroutines: 16
Total goroutines: 17
```

**Comment by akhenakh** [comment]
Editing your code like this:
```
package main

import (
        "fmt"
        "runtime"
        "time"

        "github.com/akhenakh/statgo"
)

func main() {
        go func() {
                d := time.Duration(2) * time.Second
                for range time.Tick(d) {
                        fmt.Printf("Total goroutines: %d\n", runtime.NumGoroutine())
                }
        }()

        for {
                d := time.Duration(1) * time.Second
                statgo.NewStat()
                time.Sleep(d)
        }
}
```

gives:

```
$ go run main.go 
Total goroutines: 3
Total goroutines: 3
Total goroutines: 3
Total goroutines: 3
```

**Comment by mia0x75** [comment]
it's the same.

```
$ go run main.go 
Total goroutines: 4
Total goroutines: 6
Total goroutines: 8
Total goroutines: 10
Total goroutines: 12
Total goroutines: 14
Total goroutines: 16
Total goroutines: 18
Total goroutines: 20
Total goroutines: 22
Total goroutines: 24
Total goroutines: 26
Total goroutines: 28
Total goroutines: 30
Total goroutines: 32
^Csignal: interrupt

$ go version
go version go1.11.4 linux/amd64

$ rpm -qa | grep libstat
libstatgrab-0.91-10.fc29.x86_64
libstatgrab-devel-0.91-10.fc29.x86_64
```

the code is running on Fedora 29.

**Comment by HeinOldewageRetro** [comment]
@akhenakh A new goroutine gets created at https://github.com/akhenakh/statgo/blob/master/statgo.go:27, and only exits if `<-s.exitMessage` is closed. That channel is only closed in `(s *Stat) free() ` that is set as a finalizer (`runtime.SetFinalizer(s, (*Stat).free)`)

From the documentation of SetFinalizer s will not be freed as long as it is reachable, and this goroutine will keep is reachable.

**Comment by akhenakh** [comment]
SetFinalizer is called whenever the GC wants it, since there is no reference to the pointer returned by `statgo.NewStat()` in the for loop it can be marked.

In fact it's GCed correctly on Linux

go version go1.11.4 linux/amd64
```
Total goroutines: 3
Total goroutines: 3
Total goroutines: 3
```
Again this library can't be used like this, not because of Go, but because of libstatgrab, you have to instantiate only one at a time.

**Comment by HeinOldewageRetro** [comment]
> since there is no reference to the pointer returned by statgo.NewStat() in the for loop it can be marked.

But there is a reference. 
https://github.com/akhenakh/statgo/blob/master/statgo.go#L43

```
case <-s.exitMessage:
```

I am also running go version go1.11.2 linux/amd64 and I also get the issue with the code you posted. 
I understand that this is not the expected usage of the library, but I do believe we can change the library to work in all cases.

**Comment by akhenakh** [comment]
Sure, feel free to reopen and submit a PR if needed

A better documentation is needed anyway !
