### ISSUE TITLE
sometime the CPU idle value is NaN

### ISSUE THREAD

**Issue by harlanc** [akhenakh/statgo#12]
```
s := stat.NewStat()	
go func() {
		s.CPUStats()
		time.Sleep(time.Second)
		cpus := s.CPUStats()

                cpu <- (100 - float32(cpus.Idle)) / 100 // range from 0 ~ 1

	}()
```

The above are the codes, but Why ?bug or my codes' problem?

I add some logs:

`	logger.LogDebugf("CPU Idle %f %f %f %f %f %f\n", cpus.User, cpus.Kernel, cpus.Idle, cpus.IOWait, cpus.Swap, cpus.Nice)`

All the cpus member are NaN.

**Comment by harlanc** [comment]
My scenario is that two  goroutines are reading CPU stat basically at the same time.

**Comment by akhenakh** [comment]
As it is this library is not thread safe, cause the underlying statgrab library is not.

You probably want only one goroutine to read the values, then several goroutines to compute them.
