### ISSUE TITLE
thats an oof 

### ISSUE THREAD

**Issue by TotallyNotAHaxxer** [akhenakh/statgo#14]
```
go: downloading github.com/akhenakh/statgo v0.0.0-20171021021904-3ae2cda264c5
# github.com/akhenakh/statgo
../../go/pkg/mod/github.com/akhenakh/statgo@v0.0.0-20171021021904-3ae2cda264c5/cpu_stats.go:4:11: fatal error: statgrab.h: No such file or directory
    4 | // #include <statgrab.h>
      |           ^~~~~~~~~~~~
compilation terminated.


```

maybe someone needs to fix the c,  did the make install even installed libs on my own and still got the same error, sometimes i wonder did you forget a semicolon?  :laughing:

**Comment by akhenakh** [comment]
You need to install libstatgrab and the includes on your system. 

Go is not responsible for that.

**Comment by TotallyNotAHaxxer** [comment]
i did still have received the same error as stated above, and i dont believe i have ever claimed go was the reason for the fault, upon install and compilation it failed, after it claimed i didnt have all the libs i checked and the ones i didnt have i installed ( all installs were successful )  im not new to c or C++ and even spending a hour or two nothing was working. and maybe a install script in the future would be a bit better for required libs,  its better to do so :smirk:

**Comment by TotallyNotAHaxxer** [comment]
```
, did the make install even installed libs on my own and still got the same error
```

**Comment by akhenakh** [comment]
Not sure what you are talking about there is no makefile in this project. 

You are responsible to install libstatgrab on your own, using your operating system packages or install it properly. 

Cgo is looking for include files in the standard directories. 

If not you can pass options to CGO_CFLAGS yourself.

**Comment by akhenakh** [comment]
You are misunderstanding this project libstatgrab is another project. 
This is the Go bindings for it. 
Check upstream website.

**Comment by TotallyNotAHaxxer** [comment]
did you look or read what i was saying? i said i installed all required libs and still the script was not working. as you told me " install the libs "
