### ISSUE TITLE
I get a not-a-number value using CPUStats 

### ISSUE THREAD

**Issue by dominik-preiss** [akhenakh/statgo#16]
![NaN](https://user-images.githubusercontent.com/117373897/216361838-b56aa79f-49ae-427a-ba67-87d483dc914c.JPG)
I get a NaN for some all values coming from "sg_get_cpu_percents_of" using the CPUStats(). 
Sorry, just read the comment above the function with the 100ms ...  you can delete this issue.

**Comment by DomPre1990** [comment]
![image](https://user-images.githubusercontent.com/117373897/216364948-e02320c4-6a3d-4070-a420-f3dc2bd786fd.png)
Sometimes I get just this values. But I think this is not the expected result. Unfortunately I cannot find a mistake. I am using a virtual Machine with Debian 11 (bullseye)
