### ISSUE TITLE
NetIOStats: Misleading and Incorrect

### ISSUE THREAD

**Issue by HeinOldewage** [akhenakh/statgo#2]
Two problems exist with `NetIOStats()`.
Firstly the underlying call to `sg_get_network_io_stats_diff` returns the stats from the last call or from system start up if it is the fist call. The result includes the system time that the stats were taken over. This field (systime) is not included in the struct returned by the function, making the results almost useless as no rate can be estimated.
`SysTime: time.Duration(int(v.systime))*time.Second,` can convert intervals(followup calls). 

Once the systime is included a second problem is made clear.
The underlying function depends on the fact that the same OS thread will make the call. Currently different  threads, depending on the scheduler, call the function.
Other functions might have the same drawback/problem, but I have not investigated this.
For example, if three call were made, the second one 10 seconds after the first and the third 1 second after the second then the stats for the third might be for 1 second (if it was called from the same thread as the second) or for 11 seconds(if it was called from the same thread as the first) or for the the system uptime(if it was called from a new thread). 

    stats := statgo.NewStat()
    go func() {
    	for _, netstats := range stats.NetIOStats() {
    		fmt.Println(netstats)
    	}
    }()
    go func() {
    	time.Sleep(10 * time.Second)
    	for _, netstats := range stats.NetIOStats() {
    		fmt.Println(netstats)
    	}
    }()
    go func() {
    	time.Sleep(11 * time.Second)
    	for _, netstats := range stats.NetIOStats() {
    		fmt.Println(netstats)
    	}
    }()

A solution might be to start up a goroutine (in `init()`) that is is bound to an OS thread (using `runtime.LockOSThread()`) and waits for calls on a channel.
This will unfortunately require a restructure of most of the code..

**Comment by akhenakh** [comment]
Yep I've noticed the problem exists with the Cpu counters too but less visible. 

Thanks for the detailed report I'll think about it your proposed solution sounds legit.

**Comment by akhenakh** [comment]
hey @HeinOldewage hopefully it does not change to much the interface and should solve the issue

**Comment by HeinOldewage** [comment]
Thank you for the quick feedback/fix.
I did a quick peek and it looks good.

I do have a question about `C.sg_shutdown()` in `Stat.free() `, should that not be called on the same thread as `C.sg_init(1)` ? If so that should be moved to `case <-s.exitMessage:`
I have no easy way to test this and libstatgrab's documentation does not mention anything about sg_shutdown. 

Thanks again.

**Comment by akhenakh** [comment]
The manpage does not mention the cleanup nor the initialization has to be called from the main thread, in fact only some functions are using thread local mainly I assume to maintain the time of the last call.

For consistency I would probably do it anyway.
