### ISSUE TITLE
CPUStats: Stats do not update on consecutive calls.

### ISSUE THREAD

**Issue by HeinOldewage** [akhenakh/statgo#4]
The values for User,Kernel,Idle,IOWait,Swap and Nice remain constant for every NewStat().

Replacing `C.sg_get_cpu_percents_of(C.sg_last_diff_cpu_percent, nil)` with `C.sg_get_cpu_percents_of(C.sg_new_diff_cpu_percent, nil)` gets updated stats for every call of CPUStats.

**Comment by akhenakh** [comment]
Side effect of our previous work :)
I need to setup proper testing to ensure consistency. 

Duplicate of #3

**Comment by akhenakh** [comment]
fixed in #3  
added you in the README as a contributor ;)

**Comment by HeinOldewage** [comment]
Thank you, once again, for the quick response.
Will test shortly.

And thank you for adding me as a contributor ;)
