### ISSUE TITLE
network RX WX data is 0  at Mac

### ISSUE THREAD

**Issue by hxiaodon** [akhenakh/statgo#8]
Hi,

I tried using statgo to monitor my laptop's os stat, the network IO info seems to be incorrect.(TX,RX is always zero)

Could you help to take a look? Thanks!
./migration 
User:	50.000000
Kernel:	0.000000
Idle:	50.000000
IOWait:	0.000000
Swap:	0.000000
Nice:	0.000000
LoadMin1:	2.580078
LoadMin5:	2.706055
LoadMin15:	2.521973
Period:	0
TimeTaken:	2016-06-21 22:08:34.754612291 +0800 CST

OSName:		Darwin
OSRelease:	15.5.0
OSVersion:	Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64
Platform:	x86_64
HostName:	zhangwenjingdeMacBook-Pro.local
NCPUs:		8
MaxCPUs:	8
BitWidth:	64

stat is &statgo.NetIOStats{IntName:"lo0", TX:0, RX:0, IPackets:0, OPackets:0, IErrors:0, OErrors:0, Collisions:0, Period:0, TimeTaken:time.Time{sec:63602114914, nsec:755049611, loc:(*time.Location)(0x4633c40)}}
stat is &statgo.NetIOStats{IntName:"gif0", TX:0, RX:0, IPackets:0, OPackets:0, IErrors:0, OErrors:0, Collisions:0, Period:0, TimeTaken:time.Time{sec:63602114914, nsec:755225748, loc:(*time.Location)(0x4633c40)}}
stat is &statgo.NetIOStats{IntName:"stf0", TX:0, RX:0, IPackets:0, OPackets:0, IErrors:0, OErrors:0, Collisions:0, Period:0, TimeTaken:time.Time{sec:63602114914, nsec:755375818, loc:(*time.Location)(0x4633c40)}}
stat is &statgo.NetIOStats{IntName:"en0", TX:0, RX:0, IPackets:0, OPackets:0, IErrors:0, OErrors:0, Collisions:0, Period:0, TimeTaken:time.Time{sec:63602114914, nsec:755619534, loc:(*time.Location)(0x4633c40)}}
stat is &statgo.NetIOStats{IntName:"en1", TX:0, RX:0, IPackets:0, OPackets:0, IErrors:0, OErrors:0, Collisions:0, Period:0, TimeTaken:time.Time{sec:63602114914, nsec:755722533, loc:(*time.Location)(0x4633c40)}}
stat is &statgo.NetIOStats{IntName:"en2", TX:0, RX:0, IPackets:0, OPackets:0, IErrors:0, OErrors:0, Collisions:0, Period:0, TimeTaken:time.Time{sec:63602114914, nsec:755867250, loc:(*time.Location)(0x4633c40)}}
stat is &statgo.NetIOStats{IntName:"p2p0", TX:0, RX:0, IPackets:0, OPackets:0, IErrors:0, OErrors:0, Collisions:0, Period:0, TimeTaken:time.Time{sec:63602114914, nsec:756018295, loc:(*time.Location)(0x4633c40)}}
stat is &statgo.NetIOStats{IntName:"bridge0", TX:0, RX:0, IPackets:0, OPackets:0, IErrors:0, OErrors:0, Collisions:0, Period:0, TimeTaken:time.Time{sec:63602114914, nsec:756168235, loc:(*time.Location)(0x4633c40)}}
stat is &statgo.NetIOStats{IntName:"awdl0", TX:0, RX:0, IPackets:0, OPackets:0, IErrors:0, OErrors:0, Collisions:0, Period:0, TimeTaken:time.Time{sec:63602114914, nsec:756262222, loc:(*time.Location)(0x4633c40)}}

**Comment by HeinOldewage** [comment]
More than just TX and RX is wrong, The Period is also 0, which is highly unlikely. About the only things right are the interface names (gotten from the library, so the function call to the C library succeeds) and the current time (taken from go). 

Can you post code used? I doubt there is anything there that can help us, but lets take a look. Also what version of libstatgrab are you using?

If I had to take a guess I would say there is something wrong with the libstatgrab library installed (but I don't have a Mac so I can't rule out anything else).

**Comment by akhenakh** [comment]
Can't check right now but statgo was developed on a Mac at first, so it should work :)

**Comment by akhenakh** [comment]
Try this:
```
go get github.com/stretchr/testify/assert
go test -v
```

**Comment by hxiaodon** [comment]
@akhenakh 
I ran the Unit Test cases you suggested.
		TimeTaken:	2016-06-22 10:43:49.500327048 +0800 CST
		 IntName:	en0
		TX:		317
		RX:		755
		IPackets:	7
		OPackets:	4
		IErrors:	0
		OErrors:	0
		Collisions:	0
		Period:	5s 

Seems there is no problem.  I also review the TestNetIO function, it is almost same as my local
![image](https://cloud.githubusercontent.com/assets/10990210/16253236/6ddad550-3867-11e6-837a-cf894ade0301.png)
I will try again, thanks!

**Comment by hxiaodon** [comment]
If I ran the UT with the following command
go test -v github.com/akhenakh/statgo -run TestNetIO, the Period field will be zero

		TimeTaken:	2016-06-22 11:10:24.554913225 +0800 CST
		 IntName:	en0
		TX:		0
		RX:		0
		IPackets:	0
		OPackets:	0
		IErrors:	0
		OErrors:	0
		Collisions:	0
		Period:	0

If I ran all test cases:  go test -v github.com/akhenakh/statgo
The TestNetIO result will be 
		TimeTaken:	2016-06-22 11:14:51.485171678 +0800 CST
		 IntName:	en0
		TX:		4397
		RX:		6020
		IPackets:	24
		OPackets:	22
		IErrors:	0
		OErrors:	0
		Collisions:	0
		Period:	5s
My usage has something wrong?

**Comment by hxiaodon** [comment]
I think I find the root cause. statgo need a time interval between each calling
![image](https://cloud.githubusercontent.com/assets/10990210/16254174/db4610ac-386f-11e6-827c-9aaa679b0343.png)
Now it works. Let me know if my deduction is correct.Thanks~

**Comment by HeinOldewage** [comment]
@hxiaodon You are mostly correct with your assumption about the interval statgo needs. 
The first call to any stats function (`NetIOStats`, `CPUStats`, `MemStats`) gives you stats over the period from the first NewStat() call to the current stats one, every subsequent call will give you stats for the period starting from the previous call to the current call.

Your original loop called NetIOStats for every iteration, getting new stats for every iteration, and that is why the period was 0 (and all other stats also).

I use the following loop to iterate, it is relatively clean:
```
for _, netstats := range stats.NetIOStats() {
    fmt.Println( netstats)
}
```

What would you like to use the library for? Getting periodic stats on the system, or system stats from  system start?

@akhenakh Why did we decide to throw away the averaged system uptime stats? Specifically referencing:
```		C.sg_get_cpu_stats_diff(nil)
		C.sg_get_network_io_stats_diff(nil)
		C.sg_get_page_stats_diff(nil)
		C.sg_get_disk_io_stats_diff(nil)
```
We should probably update the documentation to accurately describe the workings of the functions better (period they measure between etc), so that users unfamiliar with libstatgrab can still use the library. We should also note that the first Call to stats differ from the the first call to the library, so that user familiar with libstatgrab aren't caught off guard.
We can make this update either in the readme, or in the code/godoc, what do you think?

**Comment by hxiaodon** [comment]
@HeinOldewage 
I' m working on a data migration tool(total data size is about 40TB). To control the network stream under a threshold(e.g 40MB/s), I need read the stats of the system periodically.

**Comment by HeinOldewage** [comment]
I am not sure that libstatgrab supports durations less than one second (The duration variable is measured in seconds) . So it might be hard doing on the fly calculation to do rate limiting. 

Have you considered writing a wrapper around io.ReadWriter that writes 1MB(or some amount)  and measures how long that took, and waits if the MB/s was over the threshold?

The other problem with using this library is that it measures total system usage, so other applications' network usage will also be counted towards the threshold (maybe that is what you want? Only copying if the network is somewhat idle).

But I think the original issue is resolved?

**Comment by hxiaodon** [comment]
@HeinOldewage 
1. Seems libstatgrab does not support durations less than one second, and I did not need accurate RX/TX rate less than one second, my frequency of sampling will be 5 - 10 seconds
2. I have no plan to write  a wrapper, it does could give me an more trustable value, but it will make the code more complex for other one to maintain
3  could you recommend some other good tools/libs for the network usage of a specific process?

Yeah, the original issue has been solved!  Thank you!
